name: Tymely
options:
  bundleIdPrefix: co.tymely

targets:
  Tymely:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Components
      - path: Models
      - path: Services
      - path: Shared
      - path: Storage
      - path: Theme
      - path: Utils
      - path: Views
      - TymelyApp.swift
    resources:
      - path: Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: co.tymely.Tymely
        DEVELOPMENT_TEAM: WR5SQ3MV4C
        INFOPLIST_FILE: Info.plist
        TARGETED_DEVICE_FAMILY: 1,2
        SWIFT_VERSION: 5.0
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    entitlements:
      path: Tymely.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.tymely.app
    dependencies:
      - target: TymelyWidget
        embed: true

  TymelyWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: TymelyWidget
        excludes:
          - "*.xcassets"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: co.tymely.Tymely.TymelyWidget
        DEVELOPMENT_TEAM: WR5SQ3MV4C
        INFOPLIST_FILE: TymelyWidget/Info.plist
        TARGETED_DEVICE_FAMILY: 1,2
        SWIFT_VERSION: 5.0
        SKIP_INSTALL: true
    resources:
      - path: TymelyWidget/Assets.xcassets
    # entitlements:
    #   properties:
    #     com.apple.security.application-groups:
    #       - group.com.tymely.app